const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const ADDOPENTMENU = "ADDOPENTMENU";
const SET_OPENKEY = "SET_OPENKEY";
const SET_SELECTKEY = "SET_SELECTKEY";
export { INCREMENT, DECREMENT, ADDOPENTMENU, SET_OPENKEY, SET_SELECTKEY };
