const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const ADDOPENTMENU = "ADDOPENTMENU";
const SET_OPENKEY = "SET_OPENKEY";
const SET_SELECTKEY = "SET_SELECTKEY";
const FILTER_OPENKEY = "FILTER_OPENKEY";
export {
  INCREMENT,
  DECREMENT,
  ADDOPENTMENU,
  SET_OPENKEY,
  SET_SELECTKEY,
  FILTER_OPENKEY,
};
