const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const ADDOPENTMENU = "ADDOPENTMENU";
const SET_OPENKEY = "SET_OPENKEY";
const SET_SELECTKEY = "SET_SELECTKEY";
const FILTER_OPENKEY = "FILTER_OPENKEY";
const SET_OPENMENU = "SET_OPENMENU";
const SET_USERINFO = "SET_USERINFO";
export {
  INCREMENT,
  DECREMENT,
  ADDOPENTMENU,
  SET_OPENKEY,
  SET_SELECTKEY,
  FILTER_OPENKEY,
  SET_OPENMENU,
  SET_USERINFO,
};
