const ADDOPENTMENU = "ADDOPENTMENU";
const SET_OPENKEY = "SET_OPENKEY";
const SET_SELECTKEY = "SET_SELECTKEY";
const FILTER_OPENKEY = "FILTER_OPENKEY";
const SET_USERMENU = "SET_USERMENU";
const SETCURRENTPATH = "SETCURRENTPATH"
export {
  ADDOPENTMENU,
  SET_OPENKEY,
  SET_SELECTKEY,
  FILTER_OPENKEY,
  SET_USERMENU,
  SETCURRENTPATH
};
