export const ADDOPENTMENU = "ADDOPENTMENU";
export const SET_OPENKEY = "SET_OPENKEY";
export const SET_SELECTKEY = "SET_SELECTKEY";
export const FILTER_OPENKEY = "FILTER_OPENKEY";
export const SET_USERMENU = "SET_USERMENU";
export const SETCURRENTPATH = "SETCURRENTPATH"